version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    groups:
      ruby:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    groups:
      npm:
        patterns:
          - "*"
