queue_rules:
  - name: default
    conditions:
      - author=dependabot[bot]

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    actions:
      queue:
        method: squash
        name: default
