queue_rules:
  - name: dependabot
    conditions:
      - author=dependabot[bot]

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      queue:
        method: merge
        name: dependabot
