services:
  html2rss-web:
    image: html2rss/web:latest
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: 4000

  caddy:
    image: caddy:2-alpine
    depends_on:
      - html2rss-web
    command:
      - caddy
      - reverse-proxy
      - --from
      - ${CADDY_HOST}
      - --to
      - html2rss-web:4000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data

  watchtower:
    image: containrrr/watchtower
    depends_on:
      - html2rss-web
      - caddy
    command:
      - --cleanup
      - --interval
      - "7200"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  caddy_data:
